- hosts: Ubuntu_VM
  tasks:
  - name: Update apt apache
    apt:
      update_cache: yes

  - name: Install a list of packages
    apt:
      name:
        - apache2
        - tree
        - git
      state: present

  - name: Start service Apache and make it permanent
    service: 
      name: apache2
      state: started
      enabled: yes

  - name: Create group kaizen
    group:
      name: kaizen
      state: present

  - name: Create group devops
    group:
      name: devops
      state: present

  - name: Create group qa
    group:
      name: qa
      state: present    

  - name: Create user Bakyt
    user:
      name: Bakyt
      groups: kaizen, qa
      state: present    

  - name: Create user tester 
    user:
      name: tester
      groups: qa
      state: present   

  - name: Copy files from Homework1 to remote host 
    copy:
      src: "./"
      dest: /root/     
    

     

     
         