
- hosts: centos
  become: yes
  tasks:
  - name: Install required packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - httpd
      - wget
      - unzip
      - epel-release
      - mysql
      - mariadb
      - mariadb-server

  - name: Install Remi repository
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present

  - name: Enable PHP 7.4 repository
    command: yum-config-manager --enable remi-php74

  - name: Install PHP and PHP MySQL module
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-mysql

  - name: Download WordPress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/latest.tar.gz

  - name: Extract WordPress
    unarchive:
      src: /tmp/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
      owner: apache
      group: apache

  - name: Restart Apache
    systemd:
      name: httpd
      state: restarted
      enabled: yes

  - name: Start MariaDB
    systemd:
      name: mariadb
      state: started
      enabled: yes